function loading;
%zli
%August 2010
%
%general
global fig screen prop node elem lengths curve shapes clas springs constraints GBTcon BC m_all neigs version screen
%output from pre2
global subfig ed_prop ed_node ed_elem ed_lengths axestop screen flags modeflag ed_springs ed_constraints
%output from propout and loading
global A xcg zcg Ixx Izz Ixz thetap I11 I22 Cw J outfy_tex unsymm restrained Bas_Adv scale_w Xs Ys w scale_tex_w outPedit outMxxedit outMzzedit outM11edit outM22edit outTedit outBedit outL_Tedit outx_Tedit Pcheck Mxxcheck Mzzcheck M11check M22check Tcheck screen axesstres scale_tex maxstress_tex minstress_tex

%
%defaults
scale=1;
fy=0;
P=0;
Mxx=0;
Mzz=0;
M11=0;
M22=0;
maxstress=0;
minstress=0;
T=0;
L=100;
x=50;
B=0;
Pflag=1;
Mxxflag=1;

%loading
subfig=figure;
name=['CUFSM v',version,' -- Applied Stress Generator'];
set(subfig,'Name',name,'NumberTitle','off');
set(subfig,'MenuBar','none');
set(subfig,'position',[50 70 1024 633])%

%Define the axis for the cross-section plots
axesstres=axes('Units','normalized','Position',[0.46 0.06 0.53 0.78],'visible','off');

%calculate section properties
%[A,xcg,zcg,Ixx,Izz,Ixz,thetap,I11,I22]=grosprop(node,elem);
%[Cw, J, Xs, Ys, w, Bx, By, B1, B2]=Warp(node,elem);
[A,xcg,zcg,Ixx,Izz,Ixz,thetap,I11,I22,J,Xs,Ys,Cw,B1,B2,w] = cutwp_prop2(node(:,2:3),elem(:,2:4));
thetap=thetap*180/pi; %degrees...
Bx=NaN;, By=NaN;
%calculate initial values for yield moments
[Py,Mxx_y,Mzz_y,M11_y,M22_y]=yieldMP(node,fy,A,xcg,zcg,Ixx,Izz,Ixz,thetap,I11,I22,1);
%
%
%
%
upperbox=uicontrol(subfig,...
    'Style','frame','units','normalized',...
    'HorizontalAlignment','Left',...
    'Position',[0.0 0.85 1.0 0.15]);
lowerframe=uicontrol(subfig,...
    'Style','frame','units','normalized',...
    'Position',[0.0 0.00 0.45 0.85]);
%
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'FontName','Arial','FontSize',13,...
    'Position',[0.01 0.89 .98 0.05],...
    'String','Calculation of Loads and Moments for Generation of Stress on Member');
%YIELD MOMENTS AND LOADS
lowernote=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Left',...
    'Position',[0.01 0.77 .12 0.05],...
    'String','Moments consider:');
unsymm=uicontrol(subfig,...
    'Style','radio','units','normalized',...
    'Position',[0.13 0.78 0.14 0.05],...
    'String','Unsymmetric ',...
    'Value',1,...
    'CallBack',[...
    'loading_cb(1);']);
restrained=uicontrol(subfig,...
    'Style','radio','units','normalized',...
    'Position',[0.27 0.78 0.15 0.05],...
    'String','Restrained Bending',...
    'Value',0,...
    'CallBack',[...
    'loading_cb(2);']);

%Generate P and M based on max (yield) stress
outfy=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.70 0.30 0.05],...
    'String','Generate P and M based on max (yield) stress =');
outfy_tex=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.32 0.71 0.08 0.05],...
    'String',num2str(fy));
%
%Generate Longitudinal stresses for given T, L and x, Bimoment based on T
T_tex=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.64 0.16 0.05],...
    'String','Bimoment based on T = ');
outTedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.17 0.64 0.05 0.05],...
    'String',num2str(T));
L_tex=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.22 0.64 0.03 0.05],...
    'String','L = ');
outL_Tedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.25 0.64 0.05 0.05],...
    'String',num2str(L));
x_tex=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.3 0.64 0.03 0.05],...
    'String','x = ');
outx_Tedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.33 0.64 0.06 0.05],...
    'String',num2str(x));
%Calculate P, M and B
outyield=uicontrol(subfig,...
    'Style','push','units','normalized',...
    'Position',[0.05 0.54 0.25 0.08],...
    'String','Calculate P, M and B',...
    'Callback',[...
    'loading_cb(3);']);
btn_fycalchelp=uicontrol(subfig,...
    'Style','push','units','normalized',...
    'Position',[0.3 0.54 0.05 0.08],...
    'String','?',...
    'Callback',[...
    'cufsmhelp(7);']);
btn_fycalcwarning=uicontrol(subfig,...
    'Style','push','units','normalized',...
    'Position',[0.35 0.54 0.05 0.08],...
    'String','!',...
    'Callback',[...
    'cufsmhelp(21);']);
% P, M values and checks
outP=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.45 0.1 0.05],...
    'String','P = ');
outMxx=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.39 0.1 0.05],...
    'String','Mxx = ');
outMzz=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.33 0.1 0.05],...
    'String','Mzz = ');
outM11=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.27 0.1 0.05],...
    'String','M11 = ');
outM22=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.21 0.1 0.05],...
    'String','M22 = ');
outPedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.11 0.46 0.19 0.05],...
    'String',num2str(P),...
    'Callback',[...
    'loading_cb(6);']);
outMxxedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.11 0.40 0.19 0.05],...
    'String',num2str(Mxx),...
    'Callback',[...
    'loading_cb(6);']);
outMzzedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.11 0.34 0.19 0.05],...
    'String',num2str(Mzz),...
    'Callback',[...
    'loading_cb(6);']);
outM11edit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.11 0.28 0.19 0.05],...
    'String',num2str(M11),...
    'Callback',[...
    'loading_cb(6);']);
outM22edit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.11 0.22 0.19 0.05],...
    'String',num2str(M22),...
    'Callback',[...
    'loading_cb(6);']);
%
Pcheck=uicontrol(subfig,...
    'Style','checkbox','units','normalized',...
    'Position',[0.3 0.46 0.09 0.05],...
    'String','',...
    'Value',Pflag,...
    'Callback',[...
    'loading_cb(6);']);
Mxxcheck=uicontrol(subfig,...
    'Style','checkbox','units','normalized',...
    'Position',[0.3 0.40 0.09 0.05],...
    'String','',...
    'Value',Mxxflag,...
    'Callback',[...
    'loading_cb(6);']);
Mzzcheck=uicontrol(subfig,...
    'Style','checkbox','units','normalized',...
    'Position',[0.3 0.34 0.09 0.05],...
    'String','',...
    'Value',0,...
    'Callback',[...
    'loading_cb(6);']);
M11check=uicontrol(subfig,...
    'Style','checkbox','units','normalized',...
    'Position',[0.3 0.28 0.09 0.05],...
    'String','',...
    'Value',0,...
    'Callback',[...
    'loading_cb(6);']);
M22check=uicontrol(subfig,...
    'Style','checkbox','units','normalized',...
    'Position',[0.3 0.22 0.09 0.05],...
    'String','',...
    'Value',0,...
    'Callback',[...
    'loading_cb(6);']);
%
B_tex=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.15 0.1 0.05],...
    'String','B = ');
outBedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.11 0.16 0.19 0.05],...
    'String',num2str(B));
Tcheck=uicontrol(subfig,...
    'Style','checkbox','units','normalized',...
    'Position',[0.30 0.16 0.09 0.05],...
    'String','',...
    'Value',0,...
    'Callback',[...
    'loading_cb(6);']);
%GENERATE STRESS DISTRIBUTION
% outgen=uicontrol(subfig,...
%    'Style','text','units','normalized',...
% 	'HorizontalAlignment','Right',...
%    'Position',[0.0 0.28 0.2 0.04],...
% 	'String','Loads and Moments');
genbut=uicontrol(subfig,...
    'Style','push','units','normalized',...
    'Position',[0.03 0.05 0.17 0.08],...
    'String','Submit Stress to input',...
    'Callback',[...
    'loading_cb(4);']);
genbutclose=uicontrol(subfig,...
    'Style','push','units','normalized',...
    'Position',[0.20 0.05 0.17 0.08],...
    'String','Close (don''t Submit)',...
    'Callback',[...
    'loading_cb(5);']);
btn_genhelp=uicontrol(subfig,...
    'Style','push','units','normalized',...
    'Position',[0.37 0.05 0.05 0.08],...
    'String','?',...
    'Callback',[...
    'cufsmhelp(8);']);

%
%
%
scaletitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.45 0.00 0.08 0.04],...
    'String','Scale = ');
scale_tex=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.53 0.00 0.06 0.04],...
    'String',num2str(scale));
maxstresstitle=uicontrol(subfig,...
    'Style','text','ForegroundColor','r','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.59 0.00 0.1 0.04],...
    'String','Max Comp. = ');
maxstress_tex=uicontrol(subfig,...
    'Style','text','ForegroundColor','r','units','normalized',...
    'HorizontalAlignment','Left',...
    'Position',[0.69 0.00 0.1 0.04],...
    'String',num2str(maxstress));
minstresstitle=uicontrol(subfig,...
    'Style','text','ForegroundColor','b','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.79 0.00 0.1 0.04],...
    'String','Min Tens. = ');
minstress_tex=uicontrol(subfig,...
    'Style','text','ForegroundColor','b','units','normalized',...
    'HorizontalAlignment','Left',...
    'Position',[0.89 0.00 0.11 0.04],...
    'String',num2str(minstress));
%
%
%
read_mastan=uicontrol(subfig,...
    'Style','push','units','normalized',...
    'Position',[0.84 0.91 0.15 0.08],...
    'String','Read Forces from MASTAN',...
    'Callback',[...
    'loading_cb(100);']);

