function []=commandbar();
%BWS
%8/28/00 initiated
%Z. Li
%7/20/2010, changed command bar for version 4 of cufsm
%2016/17 added toolbar and menus
%2023 cleaned out some tools not fully functioning
%
%Note
%command bar
%buttons are the same but functionality may chnage depending on the mode the user is in
%
%
%general
global currentlocation fig screen prop node elem lengths curve shapes clas springs constraints GBTcon BC m_all neigs version screen zoombtn panbtn rotatebtn m3a m3b m3c p3a p3b p3c
%output from pre2
global subfig ed_prop ed_node ed_elem ed_lengths axestop screen flags modeflag ed_springs ed_constraints
%output from template
global prop node elem lengths springs constraints h_tex b1_tex d1_tex q1_tex b2_tex d2_tex q2_tex r1_tex r2_tex r3_tex r4_tex t_tex C Z kipin Nmm axestemp subfig
%output from propout and loading
global A xcg zcg Ixx Izz Ixz thetap I11 I22 Cw J outfy_tex unsymm restrained Bas_Adv scale_w Xs Ys w scale_tex_w outPedit outMxxedit outMzzedit outM11edit outM22edit outTedit outBedit outL_Tedit outx_Tedit Pcheck Mxxcheck Mzzcheck M11check M22check Tcheck screen axesprop axesstres scale_tex maxstress_tex minstress_tex
%output from boundary condition (Bound. Cond.)
global ed_m ed_neigs solutiontype togglesignature togglegensolution popup_BC toggleSolution Plengths Pm_all Hlengths Hm_all HBC PBC subfig lengthindex axeslongtshape longitermindex hcontainershape txt_longterm len_cur len_longterm longshape_cur jScrollPane_edm jViewPort_edm jEditbox_edm hjScrollPane_edm
%output from cFSM
global toggleglobal toggledist togglelocal toggleother ed_global ed_dist ed_local ed_other NatBasis ModalBasis toggleCouple popup_load axesoutofplane axesinplane axes3d lengthindex modeindex spaceindex longitermindex b_v_view modename spacename check_3D cutface_edit len_cur mode_cur space_cur longterm_cur modes SurfPos scale twod threed undef scale_tex
%output from compareout
global pathname filename pathnamecell filenamecell propcell nodecell elemcell lengthscell curvecell clascell shapescell springscell constraintscell GBTconcell solutiontypecell BCcell m_allcell filedisplay files fileindex modes modeindex mmodes mmodeindex lengthindex axescurve togglelfvsmode togglelfvslength curveoption ifcheck3d minopt logopt threed undef axes2dshapelarge togglemin togglelog modestoplot_tex filetoplot_tex modestoplot_title filetoplot_title checkpatch len_plot lf_plot mode_plot SurfPos cutsurf_tex filename_plot len_cur scale_tex mode_cur mmode_cur file_cur xmin_tex xmax_tex ymin_tex ymax_tex filetoplot_tex screen popup_plot filename_title2 clasopt popup_classify times_classified toggleclassify classification_results plength_cur pfile_cur togglepfiles toggleplength mlengthindex mfileindex axespart_title axes2dshape axes3dshape axesparticipation axescurvemode  modedisplay modestoplot_tex
%
%
%-----------------------------------------------------------------------------------
%Navigation and Control Buttons Across the Top
%-----------------------------------------------------------------------------------
%14 December 2015 replaced all the old buttons across the top with a
%traditional menu structure, as a result these buttons are commented out,
%they are kept for posterity and it is intended to replac them with
%uitoolbar in the future, but the icons on uitoolbar are a real pain so I
%have chosen to just proceed with the file menu only at this time. Toolbar
%was implemented in 2016/17

% btn_load=uicontrol(fig,...
% 	'Style','push','units','normalized',...
% 	'Position',[0.0 0.96 0.1 0.04],...
% 	'String','Load',...
%     'Tooltip','Load file for analysis or post-processing',...
%     'Callback',[...
%       'commandbar_cb(7);']);
% btn_save=uicontrol(fig,...
% 	'Style','push','units','normalized',...
% 	'Position',[0.1 0.96 0.1 0.04],...
% 	'String','Save',...
%     'Tooltip','Save file (save file in post-processor to name the working file)',...
%     'Callback',[...
%       'commandbar_cb(9);']);
% btn_input=uicontrol(fig,...
% 	'Style','push','units','normalized',...
% 	'Position',[0.23 0.96 0.1 0.04],...
%     'Tooltip','Prepare cross-section for analysis',...
% 	'String','Input',...
%    'Callback',[...
%       'commandbar_cb(8);']);
% btn_boundcond=uicontrol(fig,...
%       'Style','push','units','normalized',...
%       'Position',[0.33 0.96 0.1 0.04],...
%       'Tooltip','Prepare boundary conditions for analysis',...
%       'String','Bound. Cond.',...
%       'Callback',[...
%       'commandbar_cb(20);']);
% btn_cFSM=uicontrol(fig,...
% 	'Style','push','units','normalized',...
% 	'Position',[0.43 0.96 0.1 0.04],...
% 	'String','cFSM',...
%     'Tooltip','Constrained Finite Strip Method (cFSM)',...
%    'Callback',[...
%       'commandbar_cb(10);']);
% btn_analyze=uicontrol(fig,...
% 	'Style','push','units','normalized',...
% 	'Position',[0.53 0.96 0.1 0.04],...
% 	'String','Analyze',...
%     'Tooltip','Finite strip analysis',...
%    'Callback',[...
%       'commandbar_cb(11);']);
% %Removed when post and compare buttons where combined in December 2002
% % btn_post=uicontrol(fig,...
% % 	'Style','push','units','normalized',...
% % 	'Position',[0.5 0.96 0.1 0.04],...
% % 	'String','Post',...
% %     'Tooltip','Post-process finite strip results',...
% %    'Callback',[...
% %       'commandbar_cb(6);']);
% btn_compare=uicontrol(fig,...
% 	'Style','push','units','normalized',...
% 	'Position',[0.63 0.96 0.1 0.04],...
% 	'String','Post',...
%     'Tooltip','Post-process finite strip results',...
%     'Callback',[...
%       'commandbar_cb(5);']);
% %removed in favor of tooltips in Decembere 2002
% % btn_mainhelp=uicontrol(fig,...
% % 	'Style','push','units','normalized',...
% % 	'Position',[0.7 0.96 0.03 0.04],...
% % 	'String','?',...
% %     'Tooltip','Help',...
% %     'Callback',[...
% %       'cufsmhelp(1);']);
% 
% panbtn=uicontrol(fig,...
%     'Style','toggle','units','normalized',...
%     'Position',[0.75 0.965 0.02 0.03],...
%     'String','P',...
%     'Value',0,...
%     'Tooltip','Engage Pan: click and drag to move',...
%     'Callback',[...
%     'commandbar_cb(14);']);
% zoombtn=uicontrol(fig,...
% 	'Style','toggle','units','normalized',...
% 	'Position',[0.77 0.965 0.02 0.03],...
%     'String','Z',...
%     'Value',0,...
%     'Tooltip','Engage Zoom: Left Click - Zoom in, Right Click - Zoom out',...
%     'Callback',[...
%       'commandbar_cb(12);']);
% rotatebtn=uicontrol(fig,...
% 	'Style','toggle','units','normalized',...
% 	'Position',[0.79 0.965 0.02 0.03],...
%     'String','R',...
%     'Value',0,...
%     'Tooltip','Engage Free Rotate: Click and drag to rotate image',...
%     'Callback',[...
%     'commandbar_cb(13);']);
% printbtn=uicontrol(fig,...
% 	'Style','push','units','normalized',...
% 	'Position',[0.81 0.96 0.05 0.04],...
% 	'String','Print',...
%     'Tooltip','Print screen',...
%    'Callback',[...
%       'commandbar_cb(1);']);
% copybtn=uicontrol(fig,...
% 	'Style','push','units','normalized',...
% 	'Position',[0.86 0.96 0.05 0.04],...
% 	'String','Copy',...
%     'Tooltip','Copy screen to clipboard (PC) file (MAC)',...
%    'Callback',[...
%       'commandbar_cb(2);']);
% resetcufsm=uicontrol(fig,...
% 	'Style','push','units','normalized',...
% 	'Position',[0.91 0.96 0.05 0.04],...
% 	'String','Reset',...
%     'Tooltip','Reset CUFSM',...
%    'Callback',[...
%       'commandbar_cb(3);']);
% aboutcufsm=uicontrol(fig,...
% 	'Style','push','units','normalized',...
% 	'Position',[0.96 0.96 0.02 0.04],...
% 	'String','?',...
%     'Tooltip','About CUFSM',...
%    'Callback',[...
%       'commandbar_cb(200);']);
% exitcufsm=uicontrol(fig,...
% 	'Style','push','units','normalized',...
% 	'Position',[0.98 0.96 0.02 0.04],...
% 	'String','X',...
%     'Tooltip','Exit CUFSM',...
%    'Callback',[...
%       'commandbar_cb(4);']);
%------------------------------------------------------------------------------------

%---------------------------------------------------------------------
%New menu across the top like a traditional program 
%(December 2015 initiated)
%---------------------------------------------------------------------
%CUFSM
m1 = uimenu(fig,'Label','CUFSM'); 
m1a = uimenu(m1,'Label','About',...
                'Callback',[...
                'commandbar_cb(200);']);
m1b = uimenu(m1,'Label','Reset',...
                'Callback',[...
                'commandbar_cb(3);']);
m1c = uimenu(m1,'Label','Quit',...
                'Callback',[...
                'commandbar_cb(4);']);
%File
m2 = uimenu(fig,'Label','File'); 
m2a = uimenu(m2,'Label','Load',...
                'Callback',[...
                'commandbar_cb(7);']);
m2b = uimenu(m2,'Label','Save',...
                'Callback',[...
                'commandbar_cb(9);']);
m2c = uimenu(m2,'Label','Print Screen',...
                'Callback',[...
                'commandbar_cb(1);']);
%View
m3 = uimenu(fig,'Label','View'); 
m3a = uimenu(m3,'Label','Pan',...
                'Checked','off',...
                'Callback',[...
                'commandbar_cb(51);']);
m3b = uimenu(m3,'Label','Zoom',...
                'Checked','off',...
                'Callback',[...
                'commandbar_cb(52);']);
m3c = uimenu(m3,'Label','Rotate',...
                'Checked','off',...
                'Callback',[...
                'commandbar_cb(53);']);
%Input
m4 = uimenu(fig,'Label','1. Input'); 
m4a = uimenu(m4,'Label','Main Pre-processor',...
                'Callback',[...
                'commandbar_cb(8);']);
m4b = uimenu(m4,'Label','C/Z Template',...
                'Callback',[...
                'commandbar_cb(21);']);
m4c = uimenu(m4,'Label','Applied Stress Generator',...
                'Callback',[...
                'commandbar_cb(23);']);          
m4d = uimenu(m4,'Label','Lengths and End Boundary Conditions',...
                'Separator','on',...
                'Callback',[...
                'commandbar_cb(20);']);
m4e = uimenu(m4,'Label','constrained Finite Strip Method',...
                'Separator','on',...
                'Callback',[...
                'commandbar_cb(10);']);
%Analysis
m5 = uimenu(fig,'Label','2. Analysis'); 
m5a = uimenu(m5,'Label','Elastic Buckling',...
                'Callback',[...
                'commandbar_cb(11);']);
%Output
m5 = uimenu(fig,'Label','3. Output'); 
m5a = uimenu(m5,'Label','Analysis Post-Processor',...
                'Callback',[...
                'commandbar_cb(5);']);
m5b = uimenu(m5,'Label','Section Properties',...
                'Callback',[...
                'commandbar_cb(22);']);
%Extras
m6 = uimenu(fig,'Label','Extra Tools'); 
m6aa = uimenu(m6,'Label','Plastic Surface Builder',...
                'Callback',[...
                'commandbar_cb(25);']);
%these tools commented out in v5.05 Dec 2023 because not working fully
% m6aaa = uimenu(m6,'Label','Hole Effect Analysis Tool (Under Development)',...
%                 'Callback',[...
%                 'commandbar_cb(26);']);
% m6a = uimenu(m6,'Label','Import MASTAN forces',...
%                 'Callback',[...
%                 'commandbar_cb(31);']);
% m6b = uimenu(m6,'Label','Export section to MASTAN',...
%                 'Callback',[...
%                 'commandbar_cb(32);']);
m6c = uimenu(m6,'Label','CUTWP (Global Buckling Only)',...
                'Separator','on',...
                'Callback',[...
                'commandbar_cb(33);']);
%m6d = uimenu(m6,'Label','ABAQUSmaker (Generate ABAQUS inp file - Legacy)',...
%                'Separator','on',...
%                'Callback',[...
%                'commandbar_cb(34);']);

%---------------------------------------------------------------------
%Experiment with adding toolbar across the top like a traditional program
%---------------------------------------------------------------------
 t = uitoolbar(fig);
% 
% %Matlab Button
% p = uipushtool(t,'TooltipString','Toolbar push button',...
%                  'ClickedCallback',...
%                  'disp(''Clicked uipushtool.'')');
%     % Read an image
%     [img,map] = imread(fullfile(matlabroot,...
%                 'toolbox','matlab','icons','matlabicon.gif'));
%     % Convert image from indexed to truecolor
%     icon = ind2rgb(img,map);
%     %display on button
%     p.CData = icon;
% 
% %File
p2a = uipushtool(t,'TooltipString','Load',...
                'Separator','on',...
                'ClickedCallback',[...
                'commandbar_cb(7);']);
                load opendoc
                p2a.CData = cdata;
p2b = uipushtool(t,'TooltipString','Save',...
                'ClickedCallback',[...
                'commandbar_cb(9);']);
                load savedoc
                p2b.CData = cdata;
p2c = uipushtool(t,'TooltipString','Print Screen',...
                'ClickedCallback',[...
                'commandbar_cb(1);']);
                load printdoc
                p2c.CData = cdata;
spacer = uipushtool(t);
                [img,map] = imread('blank.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;
                spacer.CData = icon;
spacer = uipushtool(t);
                [img,map] = imread('blank.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;
                spacer.CData = icon;
% %Input
spacer = uipushtool(t);
                [img,map] = imread('one.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;
                spacer.CData = icon;
p4a = uipushtool(t,'TooltipString','Main Pre-processor',...
                'Separator','on',...
                'ClickedCallback',[...
                'commandbar_cb(8);']);
                [img,map] = imread('pre.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;%ind2rgb(img,map);
                p4a.CData = icon;
p4b = uipushtool(t,'TooltipString','C/Z Template',...
                'ClickedCallback',[...
                'commandbar_cb(21);']);
                [img,map] = imread('template.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;%ind2rgb(img,map);
                p4b.CData = icon;
p4c = uipushtool(t,'Tooltip','Applied Stress Generator',...
                'ClickedCallback',[...
                'commandbar_cb(23);']);          
                [img,map] = imread('stressgen.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;%ind2rgb(img,map);
                p4c.CData = icon;
p4d = uipushtool(t,'TooltipString','Lengths and End Boundary Conditions',...
                'ClickedCallback',[...
                'commandbar_cb(20);']);
                [img,map] = imread('boundcon.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;%ind2rgb(img,map);
                p4d.CData = icon;
p4e = uipushtool(t,'TooltipString','constrained Finite Strip Method',...
                'ClickedCallback',[...
                'commandbar_cb(10);']);
                [img,map] = imread('cFSM.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;%ind2rgb(img,map);
                p4e.CData = icon;
% %Analysis
spacer = uipushtool(t);
                [img,map] = imread('blank.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;
                spacer.CData = icon;
spacer = uipushtool(t);
                [img,map] = imread('two.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;
                spacer.CData = icon;
p5a = uipushtool(t,'TooltipString','Elastic Buckling',...
                'Separator','on',...
                'ClickedCallback',[...
                'commandbar_cb(11);']);
                [img,map] = imread('ebanalysis.png','BackgroundColor',[0.94 0.94 0.94]);
                icon=img;
                p5a.CData = icon;
% %Output
spacer = uipushtool(t);
                [img,map] = imread('blank.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;
                spacer.CData = icon;
spacer = uipushtool(t);
                [img,map] = imread('three.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;
                spacer.CData = icon;
p5b = uipushtool(t,'TooltipString','Post-Processor',...
                'Separator','on',...
                'ClickedCallback',[...
                'commandbar_cb(5);']);
                [img,map] = imread('post.png','BackgroundColor',[0.94 0.94 0.94]);
                icon=img;
                p5b.CData = icon;
p5c = uipushtool(t,'TooltipString','Section Properties',...
                'Separator','on',...
                'ClickedCallback',[...
                'commandbar_cb(22);']);
                [img,map] = imread('sectprop.png','BackgroundColor',[0.94 0.94 0.94]);
                icon=img;
                p5c.CData = icon;
%%Extras
spacer = uipushtool(t);
                [img,map] = imread('blank.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;
                spacer.CData = icon;
spacer = uipushtool(t);
                [img,map] = imread('blank.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;
                spacer.CData = icon;
spacer = uipushtool(t);
                [img,map] = imread('blank.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;
                spacer.CData = icon;
p6aa = uipushtool(t,'Tooltip','Plastic Surface Builder',...
                'Separator','on',...
                'ClickedCallback',[...
                'commandbar_cb(25);']);
                [img,map] = imread('plastic.png','BackgroundColor',[0.94 0.94 0.94]);
                icon=img;
                p6aa.CData = icon;
% p6aaa = uipushtool(t,'Tooltip','Hole Effect Analysis Tool (Under Development)',...
%                 'Separator','on',...
%                 'ClickedCallback',[...
%                 'commandbar_cb(26);']);
%                 [img,map] = imread('hole.png','BackgroundColor',[0.94 0.94 0.94]);
%                 icon=img;
%                 p6aaa.CData = icon;
% p6a = uipushtool(t,'Tooltip','Import MASTAN forces',...
%                 'Separator','on',...
%                 'ClickedCallback',[...
%                 'commandbar_cb(31);']);
%                 [img,map] = imread('mastanin.png','BackgroundColor',[0.94 0.94 0.94]);
%                 icon=img;
%                 p6a.CData = icon;
% p6b = uipushtool(t,'Tooltip','Export section to MASTAN',...
%                 'ClickedCallback',[...
%                 'commandbar_cb(32);']);
%                 [img,map] = imread('mastanout.png','BackgroundColor',[0.94 0.94 0.94]);
%                 icon=img;
%                 p6b.CData = icon;
p6c = uipushtool(t,'Tooltip','CUTWP (Global Buckling Only)',...
                'Separator','on',...
                'ClickedCallback',[...
                'commandbar_cb(33);']);
                [img,map] = imread('twp.png','BackgroundColor',[0.94 0.94 0.94]);
                icon=img;
                p6c.CData = icon;
%p6d = uipushtool(t,'Tooltip','ABAQUSmaker (Generate ABAQUS inp file)',...
%                'Separator','on',...
%                'ClickedCallback',[...
%                'commandbar_cb(34);']);
%                [img,map] = imread('abaqus.png','BackgroundColor',[0.94 0.94 0.94]);
%                icon=img;
%                p6d.CData = icon;
% %View
spacer = uipushtool(t);
                [img,map] = imread('blank.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;
                spacer.CData = icon;
spacer = uipushtool(t);
                [img,map] = imread('blank.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;
                spacer.CData = icon;
spacer = uipushtool(t);
                [img,map] = imread('blank.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;
                spacer.CData = icon;
p3a = uitoggletool(t,'TooltipString','Pan',...
                'Separator','on',...
                'ClickedCallback',[...
                'commandbar_cb(51);']);
                load pan;
                p3a.CData = cdata;
p3b = uitoggletool(t,'TooltipString','Zoom',...
                'ClickedCallback',[...
                'commandbar_cb(52);']);
                load zoom
                p3b.CData = zoomCData;
p3c = uitoggletool(t,'TooltipString','Rotate',...
                'ClickedCallback',[...
                'commandbar_cb(53);']);
                load rotate
                p3c.CData = cdata;
% %CUFSM
spacer = uipushtool(t);
                [img,map] = imread('blank.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;
                spacer.CData = icon;
p1a = uipushtool(t,'TooltipString','About',...
                'ClickedCallback',[...
                'commandbar_cb(200);']);
                [img,map] = imread('about.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;%ind2rgb(img,map);
                p1a.CData = icon;
p1b = uipushtool(t,'TooltipString','Reset',...
                'ClickedCallback',[...
                'commandbar_cb(3);']);
                [img,map] = imread('reset.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;%ind2rgb(img,map);
                p1b.CData = icon;
p1c = uipushtool(t,'TooltipString','Quit',...
                'ClickedCallback',[...
                'commandbar_cb(4);']);
                [img,map] = imread('quit.png','BackgroundColor',[0.94 0.94 0.94]);
                icon = img;%ind2rgb(img,map);
                p1c.CData = icon;
 
