function loading;
%bws overhaul October 2015
%
%
%general
global fig screen prop node elem lengths curve shapes clas springs constraints GBTcon BC m_all neigs version screen
%output from pre2
global subfig ed_prop ed_node ed_elem ed_lengths axestop screen flags modeflag ed_springs ed_constraints
%output from loading
global inode A xcg zcg Ixx Izz Ixz thetap I11 I22 J Xs Ys Cw B1 B2 w Pedit Bedit M11edit M22edit Mxxedit Mzzedit fyedit Pyedit Byedit M11yedit M22yedit Mxxyedit Mzzyedit PonPyedit M11onM11yedit M22onM22yedit Betaedit Thetaedit Phiedit yPonPyedit yM11onM11yedit yM22onM22yedit yBetaedit yThetaedit yPhiedit principal geometric restrained scale_tex maxstress_tex minstress_tex axesstres axesPMM firstyieldui y_inc PMMbox PMMswitch popanel
%output from load file
global filename

%
%loading

%This is code to run this stress generator as a subfigure in 2015 moved to
%a main screen
    % subfig=figure;
    % name=['CUFSM v',version,' -- Applied Stress Generator'];
    % set(subfig,'Name',name,'NumberTitle','off');
    % set(subfig,'MenuBar','none');
    % set(subfig,'position',[50 70 1024 633])%

%2015 to make this a main screen similar to others
clf
name=['CUFSM v',version,' -- Applied Stress Generator'];
set(fig,'Name',name);
subfig=fig;
%
%------------------------------------------------------------------------------------
screen=7;
commandbar;
%
%
%
%Default values
%--------------
%set the initial applied actions (stress) to zero
P=0;
M11=0;
M22=0;
Mxx=0;
Mzz=0;
B=0;
%Guess an initial Fy based on E
E=prop(1,2);
if E<30000
    fy=50;
elseif E>199000
    fy=345;
else
    fy=1;
end
%Generate initial values for the yielding and loading
[A,xcg,zcg,Ixx,Izz,Ixz,thetap,I11,I22,J,Xs,Ys,Cw,B1,B2,w] = cutwp_prop2(node(:,2:3),elem(:,2:4));
thetap=thetap*180/pi; %degrees...
%calculate initial values for yield moments
[Py,Mxxy,Mzzy,M11y,M22y]=yieldMP(node,fy,A,xcg,zcg,Ixx,Izz,Ixz,thetap,I11,I22,0);
[By]=yieldB(fy,Cw,w);
PonPy=P/Py';
M11onM11y=M11/M11y;
M22onM22y=M22/M22y;
beta=0;
ThetaMM=0;
PhiPM=0;
%plotting scale and other defaults
scale=1;
maxstress=0;
minstress=0;
flags=[0 0 0 0 1 0 0 0 0 1];
%---------------end default calculations
%
%
%
%This GUI includes the following major sections:
%Reference Applied Loads for Stress Generation
%Stress Generator Plot and Return to Input Page
%First Yield Calculator
%Generalized Demand Definition
%Yield Point along given P-M-M
%Visualization of point in the P-M-M Space
%
%GUI Interface for these secitons follow
%Reference Applied Loads for Stress Generation
%------------------------------------------------
box=uicontrol(subfig,...
    'Style','frame','units','normalized',...
    'Position',[0.0 0.70 0.25 0.30]);
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'FontName','Arial','FontSize',12,...
    'Position',[0.01 0.96 .23 0.03],...
    'String','Reference Applied Loads');
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'Position',[0.01 0.92 .23 0.03],...
    'String','for stress generation');
%P
Ptitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.88 0.05 0.03],...
    'String','P = ');
Pedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.06 0.88 0.06 0.03],...
    'String',num2str(P),...
    'Callback',[...
    'loading_cb(1);']);
%B, bimoment
Btitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.126 0.88 0.05 0.03],...
    'String','B = ');
Bedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.185 0.88 0.06 0.03],...
    'String',num2str(B),...
    'Callback',[...
    'loading_cb(1);']);
%Principal M11, M22
principal=uicontrol(subfig,...
   'Style','radio','units','normalized',...
   'Position',[0.01 0.84 0.123 0.03],...
   'String','principal or',...
   'Value',0,...
   'CallBack',[...
   'loading_cb(2);']);
M11title=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.8 0.05 0.03],...
    'String','M11 = ');
M11edit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.06 0.8 0.06 0.03],...
    'String',num2str(M11),...
    'Callback',[...
    'loading_cb(1);']);
M22title=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.76 0.05 0.03],...
    'String','M22 = ');
M22edit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.06 0.76 0.06 0.03],...
    'String',num2str(M22),...
    'Callback',[...
    'loading_cb(1);']);
%Geometric
geometric=uicontrol(subfig,...
   'Style','radio','units','normalized',...
   'Position',[0.100 0.84 0.123 0.03],...
   'String','geometric',...
   'Value',1,...
   'CallBack',[...
   'loading_cb(3);']);
Mxxtitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.126 0.8 0.05 0.03],...
    'String','Mxx = ');
Mxxedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.185 0.8 0.06 0.03],...
    'String',num2str(Mxx),...
    'Callback',[...
    'loading_cb(1);']);
Mzztitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.126 0.76 0.05 0.03],...
    'String','Mzz = ');
Mzzedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.185 0.76 0.06 0.03],...
    'String',num2str(Mzz),...
    'Callback',[...
    'loading_cb(1);']);
restrained=uicontrol(subfig,...
   'Style','checkbox','units','normalized',...
   'Position',[0.17 0.84 0.075 0.03],...
   'String','restrained',...
   'Value',1,...
   'CallBack',[...
   'loading_cb(4);']);
%read from applied stresses in pre
readstress=uicontrol(subfig,...
    'Style','pushbutton','units','normalized',...
    'Position',[0.01 0.71 0.105 0.03],...
    'String','Generate from Stress',...
    'Tooltip','Select to use current stress to estimate P,B,M, etc.',...
    'Callback',[...
    'loading_cb(200);']);
%read from mastan
% readmastan=uicontrol(subfig,...
%     'Style','pushbutton','units','normalized',...
%     'Position',[0.135 0.71 0.105 0.03],...
%     'String','Read from Mastan',...
%     'Callback',[...
%     'loading_cb(300);']);
%------------------------------------------------
%
%
%Stress Generator Plot and Return to Input Page
%------------------------------------------------
%box=uicontrol(subfig,...
%    'Style','frame','units','normalized',...
%    'Position',[0.0 0.0 0.50 0.70]);
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'FontName','Arial','FontSize',12,...
    'Position',[0.01 0.66 .48 0.03],...
    'String','Reference Cross-section Stress');
%Define the axis for the cross-section stress plots
axesstres=axes('Units','normalized','Position',[0.01 0.05 0.49 0.659-0.05],'visible','off');
%plot current applied stress
inode=node;,inode(:,8)=0*node(:,8);
%strespic(inode,elem,axesstres,scale)
crossect(inode,elem,axesstres,springs,constraints,flags)
%action buttons for submitting stress
genbut=uicontrol(subfig,...
    'Style','push','units','normalized',...
    'Position',[0.01 0.665 0.105 0.03],...
    'BackgroundColor','g',...
    'String','Submit Stress to input',...
    'Callback',[...
    'loading_cb(100);']);
btn_genhelp=uicontrol(subfig,...
    'Style','push','units','normalized',...
    'Position',[0.116 0.665 0.02 0.03],...
    'String','?',...
    'Callback',[...
    'cufsmhelp(8);']);
genbutclose=uicontrol(subfig,...
    'Style','push','units','normalized',...
    'Position',[0.138 0.665 0.02 0.03],...
    'String','X',...
    'Callback',[...
    'loading_cb(101);']);
%scale max and min
scaletitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.19 0.01 0.04 0.03],...
    'String','Scale = ');
scale_tex=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.23 0.01 0.028 0.03],...
    'String',num2str(scale),...
    'Callback',[...
    'loading_cb(1);']);
maxstresstitle=uicontrol(subfig,...
    'Style','text','ForegroundColor','r','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.26 0.01 0.06 0.03],...
    'String','Max Comp.= ');
maxstress_tex=uicontrol(subfig,...
    'Style','text','ForegroundColor','r','units','normalized',...
    'HorizontalAlignment','Left',...
    'Position',[0.32 0.01 0.06 0.03],...
    'String',num2str(maxstress));
minstresstitle=uicontrol(subfig,...
    'Style','text','ForegroundColor','b','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.38 0.01 0.06 0.03],...
    'String','Min Tens.= ');
minstress_tex=uicontrol(subfig,...
    'Style','text','ForegroundColor','b','units','normalized',...
    'HorizontalAlignment','Left',...
    'Position',[0.44 0.01 0.06 0.03],...
    'String',num2str(minstress));
%plot options
%Update, Plotting and Plot Options
popanel=uipanel(subfig,...
   'units','normalized',...
   'visible','off',...
   'Position',[0.4 0.390 0.1 0.665-0.390]);
plotoptions=uicontrol(subfig,...
	'Style','push','units','normalized',...
	'HorizontalAlignment','Center',...
   'Position',[0.41 0.665 0.08 0.03],...
   'String','Plot Options:',...
   'Callback',[...
 		'loading_cb(220);']);
%All the various plotting options
%flags:[node# element# mat# stress# stresspic coord constraints springs origin propaxis] 1 means show
togglenode=uicontrol('Parent',popanel,...
  'Style','checkbox','units','normalized',...
  'Position',[0.01 0.91 0.8 0.08],...
  'String','node #',...
  'Value',flags(1),...
  'Callback',[...
		'loading_cb(204);']);
  %'Position',[0.01 0.635 0.08 0.03],...
toggleelem=uicontrol('Parent',popanel,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.81 0.8 0.08],...
   'String','element #',...
   'Value',flags(2),...
   'Callback',[...
 		'loading_cb(205);']);
togglemat=uicontrol('Parent',popanel,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.71 0.8 0.08],...
   'String','material #',...
   'Value',flags(3),...
   'Callback',[...
 		'loading_cb(206);']);
togglestress=uicontrol('Parent',popanel,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.61 0.8 0.08],...
   'String','stress mag.',...
   'Value',flags(4),...
   'Callback',[...
 		'loading_cb(207);']);
togglestresspic=uicontrol('Parent',popanel,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.51 0.8 0.08],...
   'String','stress dist.',...
   'Value',flags(5),...
   'Callback',[...
 		'loading_cb(208);']);
togglecoord=uicontrol('Parent',popanel,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.41 0.8 0.08],...
   'String','coordinates',...
   'Value',flags(6),...
   'Callback',[...
 		'loading_cb(209);']);
toggleconstraints=uicontrol('Parent',popanel,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.31 0.8 0.08],...
   'String','constraints',...
   'Value',flags(7),...
   'Callback',[...
 		'loading_cb(210);']);
togglesprings=uicontrol('Parent',popanel,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.21 0.8 0.08],...
   'String','springs',...
   'Value',flags(8),...
   'Callback',[...
 		'loading_cb(211);']);
toggleorigin=uicontrol('Parent',popanel,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.11 0.8 0.08],...
   'String','origin',...
   'Value',flags(9),...
   'Callback',[...
 		'loading_cb(212);']);
togglepropaxis=uicontrol('Parent',popanel,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.01 0.8 0.08],...
   'String','centroidal axes',...
   'Value',flags(10),...
   'Callback',[...
 		'loading_cb(213);']);    
%------------------------------------------------
%
%
%First Yield Calculator
%------------------------------------------------
box=uicontrol(subfig,...
    'Style','frame','units','normalized',...
    'Position',[0.25 0.70 0.25 0.3]);
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'FontName','Arial','FontSize',12,...
    'Position',[0.26 0.96 .23 0.03],...
    'String','First Yield Calculator');
%fy
fytitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.25+0.04 0.92 0.05 0.03],...
    'String','Fy = ');
fyedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.25+0.09 0.92 0.06 0.03],...
    'String',num2str(fy),...
    'Callback',[...
    'loading_cb(11);']);
%Py
Pytitle=uicontrol(subfig,...
    'Style','pushbutton','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.25+0.01 0.88 0.049 0.03],...
    'String','Py = ',...
    'Callback',[...
    'loading_cb(12);']);
Pyedit=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.25+0.06 0.88 0.06 0.03],...
    'String',num2str(Py),...
    'Callback',[...
    'loading_cb(1);']);
%B, bimoment
Bytitle=uicontrol(subfig,...
    'Style','pushbutton','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.25+0.126 0.88 0.049 0.03],...
    'String','By = ',...
    'Callback',[...
    'loading_cb(13);']);
Byedit=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.25+0.176 0.88 0.06 0.03],...
    'String',num2str(By),...
    'Callback',[...
    'loading_cb(1);']);
%Principal M11, M22
label=uicontrol(subfig,...
   'Style','text','units','normalized',...
   'Position',[0.25+0.01 0.84 0.123 0.03],...
   'HorizontalAlignment','Left',...
   'String','principal:');
M11ytitle=uicontrol(subfig,...
    'Style','pushbutton','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.25+0.01 0.8 0.049 0.03],...
    'String','M11y = ',...
    'Callback',[...
    'loading_cb(14);']);
M11yedit=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.25+0.06 0.8 0.06 0.03],...
    'String',num2str(M11y),...
    'Callback',[...
    'loading_cb(1);']);
M22ytitle=uicontrol(subfig,...
    'Style','pushbutton','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.25+0.01 0.76 0.049 .03],...
    'String','M22y = ',...
    'Callback',[...
    'loading_cb(15);']);
M22yedit=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.25+0.06 0.76 0.06 0.03],...
    'String',num2str(M22y),...
    'Callback',[...
    'loading_cb(1);']);
%Geometric
label=uicontrol(subfig,...
   'Style','text','units','normalized',...
   'Position',[0.25+0.126 0.84 0.123 0.03],...
    'HorizontalAlignment','Left',...
   'String','geometric:');
Mxxytitle=uicontrol(subfig,...
    'Style','pushbutton','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.25+0.126 0.8 0.049 0.03],...
    'String','Mxxy = ',...
    'Callback',[...
    'loading_cb(16);']);
Mxxyedit=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.25+0.176 0.8 0.06 0.03],...
    'String',num2str(Mxxy),...
    'Callback',[...
    'loading_cb(1);']);
Mzzytitle=uicontrol(subfig,...
    'Style','pushbutton','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.25+0.126 0.76 0.049 0.03],...
    'String','Mzzy = ',...
        'Callback',[...
    'loading_cb(17);']);
Mzzyedit=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.25+0.176 0.76 0.06 0.03],...
    'String',num2str(Mzzy),...
    'Callback',[...
    'loading_cb(1);']);
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'Position',[0.26 0.72 .23 0.03],...
    'String','Push buttons to use first yield as demand');
%------------------------------------------------
%
%
%Generalized Demand Definition
%------------------------------------------------
box=uicontrol(subfig,...
    'Style','frame','units','normalized',...
    'Position',[0.50 0.7 0.25 0.3]);
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'FontName','Arial','FontSize',12,...
    'Position',[0.51 0.96 .23 0.03],...
    'String','Generalized PMM Demand Definition');
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'Position',[0.51 0.92 .23 0.03],...
    'String','based on reference applied loads');
%P-M-M Normalized Demand
label=uicontrol(subfig,...
   'Style','text','units','normalized',...
   'Position',[0.5+0.01 0.88 0.123 0.03],...
   'HorizontalAlignment','Left',...
   'String','P-M-M Normalized:');
PonPytitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.5+0.01 0.84 0.059 0.03],...
    'String','P/Py = ');
PonPyedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.5+0.07 0.84 0.05 0.03],...
    'String',num2str(PonPy),...
    'Callback',[...
    'loading_cb(20);']);
M11onM11yytitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.5+0.01 0.8 0.059 0.03],...
    'String','M11/M11y = ');
M11onM11yedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.5+0.07 0.8 0.05 0.03],...
    'String',num2str(M11onM11y),...
    'Callback',[...
    'loading_cb(20);']);
M22onM22ytitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.5+0.01 0.76 0.059 .03],...
    'String','M22/M22y = ');
M22onM22yedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.5+0.07 0.76 0.05 0.03],...
    'String',num2str(M22onM22y),...
    'Callback',[...
    'loading_cb(20);']);
%Beta-Theta-Phi
label=uicontrol(subfig,...
   'Style','text','units','normalized',...
   'Position',[0.5+0.126 0.88 0.123 0.03],...
    'HorizontalAlignment','Center',...
   'String','Beta-Theta-Phi:');
Betatitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.5+0.126 0.84 0.059 0.03],...
    'String','Beta = ');
Betaedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.5+0.185 0.84 0.05 0.03],...
    'String',num2str(beta),...
    'Callback',[...
    'loading_cb(21);']);
Thetatitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.5+0.126 0.8 0.059 0.03],...
    'String','ThetaMM = ');
Thetaedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.5+0.185 0.8 0.05 0.03],...
    'String',num2str(ThetaMM),...
    'Callback',[...
    'loading_cb(21);']);
Phititle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.5+0.126 0.76 0.059 0.03],...
    'String','PhiPM = ');
Phiedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.5+0.185 0.76 0.05 0.03],...
    'String',num2str(PhiPM),...
    'Callback',[...
    'loading_cb(21);']);
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'Position',[0.51 0.72 .23 0.03],...
    'String','Edit Normalized Demands to Change Loading');
%------------------------------------------------
%
%
%Yield Point along given P-M-M
%------------------------------------------------
box=uicontrol(subfig,...
    'Style','frame','units','normalized',...
    'Position',[0.75 0.7 0.25 0.3]);
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'FontName','Arial','FontSize',12,...
    'Position',[0.76 0.96 .23 0.03],...
    'String','Generalized PMM Yield Point');
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'Position',[0.76 0.92 .23 0.03],...
    'String','based on Fy and proportional loading');
%P-M-M Normalized Yield Point Location
label=uicontrol(subfig,...
   'Style','text','units','normalized',...
   'Position',[0.75+0.01 0.88 0.123 0.03],...
   'HorizontalAlignment','Left',...
   'String','P-M-M at yield point:');
PonPytitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.75+0.01 0.84 0.059 0.03],...
    'String','P/Py = ');
yPonPyedit=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.75+0.07 0.84 0.05 0.03],...
    'String',num2str(PonPy),...
    'Callback',[...
    'loading_cb(1);']);
M11onM11yytitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.75+0.01 0.8 0.059 0.03],...
    'String','M11/M11y = ');
yM11onM11yedit=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.75+0.07 0.8 0.05 0.03],...
    'String',num2str(M11onM11y),...
    'Callback',[...
    'loading_cb(1);']);
M22onM22ytitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.75+0.01 0.76 0.059 .03],...
    'String','M22/M22y = ');
yM22onM22yedit=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.75+0.07 0.76 0.05 0.03],...
    'String',num2str(M22onM22y),...
    'Callback',[...
    'loading_cb(1);']);
%Beta-Theta-Phi Yield Point location
label=uicontrol(subfig,...
   'Style','text','units','normalized',...
   'Position',[0.75+0.126 0.88 0.123 0.03],...
    'HorizontalAlignment','Center',...
   'String','Beta-Theta-Phi at yield point:');
Betatitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.75+0.126 0.84 0.059 0.03],...
    'String','Beta = ');
yBetaedit=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.75+0.185 0.84 0.05 0.03],...
    'String',num2str(beta),...
    'Callback',[...
    'loading_cb(1);']);
Thetatitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.75+0.126 0.8 0.059 0.03],...
    'String','ThetaMM = ');
yThetaedit=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.75+0.185 0.8 0.05 0.03],...
    'String',num2str(ThetaMM),...
    'Callback',[...
    'loading_cb(1);']);
Phititle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.75+0.126 0.76 0.059 0.03],...
    'String','PhiPM = ');
yPhiedit=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.75+0.185 0.76 0.05 0.03],...
    'String',num2str(PhiPM),...
    'Callback',[...
    'loading_cb(1);']);
%------------------------------------------------
%
%
%Visualization of point in the P-M-M Space
box=uicontrol(subfig,...
    'Style','frame','units','normalized',...
    'Position',[0.5 0.0 0.001 0.7]);
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'FontName','Arial','FontSize',12,...
    'Position',[0.61 0.66 .26 0.03],...
    'String','Generalized PMM Demand Visualization');
v1=uicontrol(subfig,...
    'Style','pushbutton','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.51 0.66 0.018 0.03],...
    'String','1',...
    'Tooltip','M11-M22 view',...
    'Callback',[...
    'loading_cb(51);']);
v2=uicontrol(subfig,...
    'Style','pushbutton','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.53 0.66 0.018 0.03],...
    'String','2',...
    'Tooltip','P-M11 view',...
    'Callback',[...
    'loading_cb(52);']);
v3=uicontrol(subfig,...
    'Style','pushbutton','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.55 0.66 0.018 0.03],...
    'String','3',...
    'Tooltip','P-M22 view',...
    'Callback',[...
    'loading_cb(53);']);
v4=uicontrol(subfig,...
    'Style','pushbutton','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.57 0.66 0.018 0.03],...
    'String','4',...
    'Tooltip','iso view',...
    'Callback',[...
    'loading_cb(54);']);
vr=uicontrol(subfig,...
    'Style','pushbutton','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.59 0.66 0.018 0.03],...
    'String','R',...
    'Tooltip','rotate on',...
    'Callback',[...
    'loading_cb(55);']);
firstyieldui=uicontrol(subfig,...
   'Style','checkbox','units','normalized',...
   'Position',[0.87 0.66 0.10 0.03],...
   'String','first yield surface',...
   'Value',1,...
   'CallBack',[...
   'loading_cb(1);']);
%finer first yield values
ysincbutton=uicontrol(subfig,...
    'Style','pushbutton','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.97 0.66 0.02 0.03],...
    'String','>',...
    'Tooltip','Select for finer yield surface discretization',...
    'Callback',[...
    'loading_cb(25);']);
ysincbutton=uicontrol(subfig,...
    'Style','pushbutton','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.95 0.66 0.02 0.03],...
    'String','<',...
    'Tooltip','Select for coarser yield surface discretization',...
    'Callback',[...
    'loading_cb(26);']);
%PMM reveal button
PMMbox=uicontrol(subfig,...
    'Style','frame','units','normalized',...
    'Position',[0.5 0.0 0.5 1.0]);
PMMswitch=uicontrol(subfig,...
    'Style','toggle','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.96 0.96 0.03 0.03],...
    'String','PMM',...
    'Tooltip','Activate PMM representation',...
    'Value',0,...
    'Callback',[...
    'loading_cb(400);']);
%Define the axes for generalized demand plots
axesPMM1=axes('Units','normalized','Position',[0.56 0.39 0.49/2-0.08 0.65/2-0.08],'visible','off');
axesPMM2=axes('Units','normalized','Position',[0.79 0.39 0.49/2-0.08 0.65/2-0.08],'visible','off');
axesPMM3=axes('Units','normalized','Position',[0.56 0.06 0.49/2-0.08 0.65/2-0.08],'visible','off');
axesPMM4=axes('Units','normalized','Position',[0.79 0.06 0.49/2-0.08 0.65/2-0.08],'visible','off');
axesPMM =[axesPMM1 axesPMM2 axesPMM3 axesPMM4];
%plot current PMM visualization
firstyieldflag=0; y_inc=10;
%PMMplotter(axesPMM,node,elem,P,M11,M22,Py,M11y,M22y,firstyieldflag,fy,y_inc)



