function plasticbuild;
%BWS February 2016
%
%general
global fig screen prop node elem lengths curve shapes clas springs constraints GBTcon BC m_all neigs version screen
%output from pre2
global subfig ed_prop ed_node ed_elem ed_lengths axestop screen flags modeflag ed_springs ed_constraints
%output from load file
global filename
%output from plasticbuild
global fib nfibedit fyedit gradesedit degreesedit axesfibersect popanel axesPMM rawpointsui gridui gridedgeui gridptsui Dthetaedit Dphiedit M11ponM11yedit M22ponM22yedit M11pedit M22pedit Ppanchoredit Thetaedit Phiedit Betapedit M11pr M22pr Ppr M11p M22p Pp

%This is code to run this plastic surface builder as a subfigure
%comment out and uncomment section below depending on how interface desired
% subfig=figure;
% name=['CUFSM v',version,' -- Plastic Surface Builder'];
% set(subfig,'Name',name,'NumberTitle','off');
% set(subfig,'MenuBar','none');
% set(subfig,'position',[50 70 1024 633])%

%This is code to run this plastic surface builder in the main screen
clf
pause(0.01)
name=['CUFSM v',version,' -- Plastic Surface Builder'];
set(fig,'Name',name);
subfig=fig;
screen=8;
commandbar;
%
%------------------------------------------------------------------------------------
%
%
%
%Default values
%--------------
%Guess an initial Fy based on E
E=prop(1,2);
if E<30000
    fy=50;
elseif E>199000
    fy=345;
else
    fy=1;
end
%plotting defaults
flags=[0 0 0 0 0 0 0 0 0 1];
%
%Default number of fibers through the section
nfib=3;
    nfiber=ones(length(elem(:,1)),1)*nfib;
    fib = fiber4elem(node,elem,nfiber);   
%Default Deg= Angular discritization for moving the neutral axis
Deg=[0:0.1:5 6:87 88:0.1:92 93:177 178:0.1:182 183:267 268:0.1:272 273:354 355:0.1:360];
%Deg=[0:10:360];
%Default Ne= radial discritization for moving the neutral axis
Ne=350;
%Ne=10;
%Initial fiber discretization
nfiber=ones(length(elem(:,1)),1)*nfib;
fib = fiber4elem(node,elem,nfiber);
%initial discretization angles
Dtheta=5;
Dphi=5;
%initial anchor values
M11ponM11y=NaN;
M22ponM22y=NaN;
M11panchor=NaN;
M22panchor=NaN;
Ppanchor=NaN;
%intitial thetaMM and phiPM and Fy
    %Use current stress to estimate the applied actions
    [A,xcg,zcg,Ixx,Izz,Ixz,thetap,I11,I22,J,Xs,Ys,Cw,B1,B2,w] = cutwp_prop2(node(:,2:3),elem(:,2:4));
    [P,M11,M22,B,err] = stress_to_action(node,xcg,zcg,thetap,A,I11,I22,w,Cw);
    fy=max(abs(node(:,8))); %guess at fy assuming max stress in the model = fy
    %If a generated action is really small we should set it to zero
    %lets say if the action is less than 0.1% of the yield for that
    %action then we set it to zero, so we need the yield then we can
    %make the corrections as needed
    %find the yield values
    [Py,Mxxy,Mzzy,M11y,M22y]=yieldMP(node,fy,A,xcg,zcg,Ixx,Izz,Ixz,thetap,I11,I22,1);
    [By]=yieldB(fy,Cw,w);
    %correct as needed
    if abs(P/Py)<0.001, P=0;, end
    if abs(B/By)<0.001, B=0;, end
    if abs(M11/M11y)<0.001, M11=0;, end
    if abs(M22/M22y)<0.001, M22=0;, end     
    %convert to theta and phi
    [beta,theta,phi] = PMMtoBetaThetaPhi(P/Py,M11/M11y,M22/M22y);
M11pr=0;
M22pr=0;
Ppr=0;
M11p=0;
M22p=0;
Pp=0;
%---------------end default calculations
%
%
%
%BASIC INPUTS
%------------------------------------------------
box=uicontrol(subfig,...
    'Style','frame','units','normalized',...
    'Position',[0.0 0.70 0.5 0.30]);
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'FontName','Arial','FontSize',12,...
    'Position',[0.01 0.96 .47 0.03],...
    'String','Plastic Surface Construction');
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'Position',[0.01 0.92 .23 0.03],...
    'String','through thickness discretization and yield stress');
%Number of Fibers
nfibtitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.88 0.05 0.03],...
    'String','nfib = ');
nfibedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.06 0.88 0.06 0.03],...
    'String',num2str(nfib),...
    'Callback',[...
    'plasticbuild_cb(1);']);
%Yield Stress
fytitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.13 0.88 0.05 0.03],...
    'String','Fy = ');
fyedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.18 0.88 0.06 0.03],...
    'String',num2str(fy),...
    'Callback',[...
    'plasticbuild_cb(12);']);
%plastic surface controls
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'Position',[0.01 0.84 .23 0.03],...
    'String','for raw plastic surface constructon');
%Number of gradations through section at a given angle
gradestitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.80 0.05 0.03],...
    'String','grades = ');
gradesedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.06 0.80 0.06 0.03],...
    'String',num2str(Ne),...
    'Callback',[...
    'plasticbuild_cb(3);']);
%explanation of grades and angles
rawinfobutton=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.13 0.80 0.01 0.03],...
   'String','?',...
   'CallBack',[...
   'plasticbuild_cb(900);']);
%Coarse and fine buttons for raw discretization
coarsebutton=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.145 0.80 0.045 0.03],...
   'String','<Coarse',...
   'CallBack',[...
   'plasticbuild_cb(5);']);
fineebutton=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.195 0.80 0.045 0.03],...
   'String','Fine>',...
   'CallBack',[...
   'plasticbuild_cb(6);']);
%Number of angles to build initial mesh on
degreestitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.76 0.05 0.03],...
    'String','angles = ');
degreesedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.06 0.76 0.18 0.03],...
    'String',num2str(Deg),...
    'Callback',[...
    'plasticbuild_cb(4);']);
%Build Raw Plastic Sruface
buildsurface=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.02 0.71 0.21 0.04],...
   'String','Build Raw Plastic Surface',...
   'CallBack',[...
   'plasticbuild_cb(10);']);
%Increments for interpolating plastic surface for viewing
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'Position',[0.01+0.25 0.84 .23 0.03],...
    'String','theta and phi increments for gridded surface');
%Delta Theta
Dthetatitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01+0.25 0.80 0.05 0.03],...
    'String','Dtheta = ');
Dthetaedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.06+0.25 0.80 0.06 0.03],...
    'String',num2str(Dtheta),...
    'Callback',[...
    'plasticbuild_cb(11);']);
%Delta Phi
Dphititle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01+0.25 0.76 0.05 0.03],...
    'String','Dphi = ');
Dphiedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.06+0.25 0.76 0.06 0.03],...
    'String',num2str(Dphi),...
    'Callback',[...
    'plasticbuild_cb(12);']);
gridinfobutton=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.13+0.25 0.80 0.01 0.03],...
   'String','?',...
   'CallBack',[...
   'plasticbuild_cb(901);']);
%Coarse and fine buttons for gridded discretization
coarsebutton2=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.145+0.25 0.80 0.045 0.03],...
   'String','<Coarse',...
   'CallBack',[...
   'plasticbuild_cb(7);']);
fineebutton2=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.195+0.25 0.80 0.045 0.03],...
   'String','Fine>',...
   'CallBack',[...
   'plasticbuild_cb(8);']);
%Grid Plastic Sruface
gridsurface=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.02+0.25 0.71 0.21 0.04],...
   'String','Grid/Interpolate Plastic Surface',...
   'CallBack',[...
   'plasticbuild_cb(11);']);


%------------------------------------------------
%
%
%CROSS-SECTION PLOT
%------------------------------------------------
%box=uicontrol(subfig,...
%    'Style','frame','units','normalized',...
%    'Position',[0.0 0.0 0.50 0.70]);
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'FontName','Arial','FontSize',12,...
    'Position',[0.01 0.66 .48 0.03],...
    'String','Cross-Section with Fiber Discretization');
%Define the axis for the cross-section stress plots
axesfibersect=axes('Units','normalized','Position',[0.01 0.05 0.49 0.6],'visible','off');
%plot current applied stress
inode=node;,inode(:,8)=0*node(:,8);
%strespic(inode,elem,axesstres,scale)
crossect(inode,elem,axesfibersect,springs,constraints,flags)
fibplotoverlay(node,elem,nfiber,fib)

%plot options
%Update, Plotting and Plot Options
popanel=uipanel(subfig,...
   'units','normalized',...
   'visible','off',...
   'Position',[0.4 0.390 0.1 0.665-0.390]);
plotoptions=uicontrol(subfig,...
	'Style','push','units','normalized',...
	'HorizontalAlignment','Center',...
   'Position',[0.41 0.665 0.08 0.03],...
   'String','Plot Options:',...
   'Callback',[...
 		'plasticbuild_cb(220);']);
%All the various plotting options
%flags:[node# element# mat# stress# stresspic coord constraints springs origin propaxis] 1 means show
togglenode=uicontrol('Parent',popanel,...
  'Style','checkbox','units','normalized',...
  'Position',[0.01 0.91 0.8 0.08],...
  'String','node #',...
  'Value',flags(1),...
  'Callback',[...
		'plasticbuild_cb(204);']);
  %'Position',[0.01 0.635 0.08 0.03],...
toggleelem=uicontrol('Parent',popanel,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.81 0.8 0.08],...
   'String','element #',...
   'Value',flags(2),...
   'Callback',[...
 		'plasticbuild_cb(205);']);
togglemat=uicontrol('Parent',popanel,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.71 0.8 0.08],...
   'String','material #',...
   'Value',flags(3),...
   'Callback',[...
 		'plasticbuild_cb(206);']);
togglestress=uicontrol('Parent',popanel,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.61 0.8 0.08],...
   'String','stress mag.',...
   'Value',flags(4),...
   'Callback',[...
 		'plasticbuild_cb(207);']);
togglestresspic=uicontrol('Parent',popanel,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.51 0.8 0.08],...
   'String','stress dist.',...
   'Value',flags(5),...
   'Callback',[...
 		'plasticbuild_cb(208);']);
togglecoord=uicontrol('Parent',popanel,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.41 0.8 0.08],...
   'String','coordinates',...
   'Value',flags(6),...
   'Callback',[...
 		'plasticbuild_cb(209);']);
toggleconstraints=uicontrol('Parent',popanel,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.31 0.8 0.08],...
   'String','constraints',...
   'Value',flags(7),...
   'Callback',[...
 		'plasticbuild_cb(210);']);
togglesprings=uicontrol('Parent',popanel,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.21 0.8 0.08],...
   'String','springs',...
   'Value',flags(8),...
   'Callback',[...
 		'plasticbuild_cb(211);']);
toggleorigin=uicontrol('Parent',popanel,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.11 0.8 0.08],...
   'String','origin',...
   'Value',flags(9),...
   'Callback',[...
 		'plasticbuild_cb(212);']);
togglepropaxis=uicontrol('Parent',popanel,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.01 0.8 0.08],...
   'String','centroidal axes',...
   'Value',flags(10),...
   'Callback',[...
 		'plasticbuild_cb(213);']);    
%------------------------------------------------

%--------------------------------------------
%PLASTIC OUTPUTS
%------------------------------------------------
box=uicontrol(subfig,...
    'Style','frame','units','normalized',...
    'Position',[0.5 0.7 0.5 0.3]);
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'FontName','Arial','FontSize',12,...
    'Position',[0.51 0.96 .48 0.03],...
    'String','Plastic Outputs');

%Plastic P-M-M at anchors
label=uicontrol(subfig,...
   'Style','text','units','normalized',...
   'Position',[0.51 0.92 0.123 0.03],...
   'HorizontalAlignment','Left',...
   'String','Plastic Anchors:');
M11ponM11ytitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.51 0.88 0.089 0.03],...
    'String','M11p/M11y = ');
M11ponM11ytitle2=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Left',...
    'Position',[0.66 0.88 0.089 0.03],...
    'String',' = Z11/S11');
M11ponM11yedit=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.6 0.88 0.05 0.03],...
    'String',num2str(M11ponM11y));
M22ponM22y=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.51 0.84 0.089 0.03],...
    'String','M22p/M22y = ');
M22ponM22ytitle2=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Left',...
    'Position',[0.66 0.84 0.089 0.03],...
    'String',' = Z22/S22');
M22ponM22yedit=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.6 0.84 0.05 0.03],...
    'String',num2str(NaN));
M11ptitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.51 0.8 0.089 0.03],...
    'String','M11p = ');
M11pedit=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.6 0.8 0.05 0.03],...
    'String',num2str(M11panchor));
M22ptitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.51 0.76 0.089 0.03],...
    'String','M22p = ');
M22pedit=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.6 0.76 0.05 0.03],...
    'String',num2str(M22panchor));
Pptitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.51 0.72 0.089 0.03],...
    'String','Pp = ');
Ppanchoredit=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.6 0.72 0.05 0.03],...
    'String',num2str(Ppanchor));
%Find Plastic Anchors
% plasticanchors=uicontrol(subfig,...
%    'Style','push','units','normalized',...
%    'Position',[0.02+0.5 0.71 0.21 0.04],...
%    'String','Calculate Plastic Anchors',...
%    'CallBack',[...
%    'plasticbuild_cb(12);']);



label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'Position',[0.76 0.92 .23 0.03],...
    'String','yield and plastic for a given angle');
%Selected angles in P-M-M space
label=uicontrol(subfig,...
   'Style','text','units','normalized',...
   'Position',[0.75+0.01 0.88 0.123 0.03],...
   'HorizontalAlignment','Left',...
   'String','Input Angles:');
Thetatitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.75+0.01 0.84 0.059 0.03],...
    'String','ThetaMM = ');
Thetaedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.75+0.07 0.84 0.05 0.03],...
    'String',num2str(theta),...
    'Callback',[...
    'plasticbuild_cb(13);']);
Phititle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.75+0.01 0.8 0.059 0.03],...
    'String','PhiPM = ');
Phiedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.75+0.07 0.8 0.05 0.03],...
    'String',num2str(phi),...
    'Callback',[...
    'plasticbuild_cb(13);']);
%Beta yield and plastic on the angle
label=uicontrol(subfig,...
   'Style','text','units','normalized',...
   'Position',[0.75+0.126 0.88 0.123 0.03],...
    'HorizontalAlignment','Center',...
   'String','Output Betas:');
Betaptitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.75+0.126 0.8 0.059 0.03],...
    'String','BetaP = ');
Betapedit=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.75+0.185 0.8 0.05 0.03],...
    'String',num2str(NaN));
%Find BETA Plastic 
% plasticanchors=uicontrol(subfig,...
%    'Style','push','units','normalized',...
%    'Position',[0.02+0.75 0.71 0.21 0.04],...
%    'String','Calculate Beta Plastic',...
%    'CallBack',[...
%    'plasticbuild_cb(13);']);
%------------------------------------------------



%----------------------------------------------
%
%PLASTIC SURFACE PLOT
%Visualization of point in the P-M-M Space
box=uicontrol(subfig,...
    'Style','frame','units','normalized',...
    'Position',[0.5 0.0 0.001 0.7]);
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'FontName','Arial','FontSize',12,...
    'Position',[0.61 0.66 .14 0.03],...
    'String','Plastic Surface Visualization');
v1=uicontrol(subfig,...
    'Style','pushbutton','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.51 0.66 0.018 0.03],...
    'String','1',...
    'Tooltip','M11-M22 view',...
    'Callback',[...
    'plasticbuild_cb(51);']);
v2=uicontrol(subfig,...
    'Style','pushbutton','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.53 0.66 0.018 0.03],...
    'String','2',...
    'Tooltip','P-M11 view',...
    'Callback',[...
    'plasticbuild_cb(52);']);
v3=uicontrol(subfig,...
    'Style','pushbutton','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.55 0.66 0.018 0.03],...
    'String','3',...
    'Tooltip','P-M22 view',...
    'Callback',[...
    'plasticbuild_cb(53);']);
v4=uicontrol(subfig,...
    'Style','pushbutton','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.57 0.66 0.018 0.03],...
    'String','4',...
    'Tooltip','iso view',...
    'Callback',[...
    'plasticbuild_cb(54);']);
vr=uicontrol(subfig,...
    'Style','pushbutton','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.59 0.66 0.018 0.03],...
    'String','R',...
    'Tooltip','rotate on',...
    'Callback',[...
    'plasticbuild_cb(55);']);
rawpointsui=uicontrol(subfig,...
   'Style','checkbox','units','normalized',...
   'Position',[0.75 0.66 0.06 0.03],...
   'String','raw points',...
   'Value',0,...
   'CallBack',[...
   'plasticbuild_cb(50);']);
gridui=uicontrol(subfig,...
   'Style','checkbox','units','normalized',...
   'Position',[0.81 0.66 0.06 0.03],...
   'String','grid surf',...
   'Value',0,...
   'CallBack',[...
   'plasticbuild_cb(50);']);
gridedgeui=uicontrol(subfig,...
   'Style','checkbox','units','normalized',...
   'Position',[0.87 0.66 0.06 0.03],...
   'String','grid edge',...
   'Value',0,...
   'CallBack',[...
   'plasticbuild_cb(50);']);
gridptsui=uicontrol(subfig,...
   'Style','checkbox','units','normalized',...
   'Position',[0.93 0.66 0.06 0.03],...
   'String','grid points',...
   'Value',0,...
   'CallBack',[...
   'plasticbuild_cb(50);']);
%finer first yield values
% ysincbutton=uicontrol(subfig,...
%     'Style','pushbutton','units','normalized',...
%     'HorizontalAlignment','Right',...
%     'Position',[0.97 0.66 0.02 0.03],...
%     'String','>',...
%     'Tooltip','Select for finer yield surface discretization',...
%     'Callback',[...
%     'plasticbuild_cb(25);']);
% ysincbutton=uicontrol(subfig,...
%     'Style','pushbutton','units','normalized',...
%     'HorizontalAlignment','Right',...
%     'Position',[0.95 0.66 0.02 0.03],...
%     'String','<',...
%     'Tooltip','Select for coarser yield surface discretization',...
%     'Callback',[...
%     'plasticbuild_cb(26);']);
axesPMM=axes('Units','normalized','Position',[0.55 0.05 0.40 0.60],'visible','off');
    rawpts=0;, gridpts=0;, betaray=0;
    PMMplasticplotter(axesPMM,M11pr,M22pr,Ppr,0,M11p,M22p,Pp,0,0,0,0,0,0)

%
