function []=template()
%BWS
%August 2000
%Template for entering in Cs and Zs
%2015 modified to handle r=0 sharp corner model generation and d=0
%track/unlipped section generation all with the same code.
%2015 added element discretization control to template
%2015 added saving section directly from template (so e.g. round and sharp can
%be saved then move on to processing the results).
%
%general
global fig screen prop node elem lengths curve shapes clas springs constraints GBTcon BC m_all neigs version screen
%output from pre2
global subfig ed_prop ed_node ed_elem ed_lengths axestop screen flags modeflag ed_springs ed_constraints
%output from template
global prop node elem lengths springs constraints h_title h_tex b1_title b1_tex d1_title d1_tex q1_title q1_tex b2_title b2_tex d2_title d2_tex q2_title q2_tex r1_title r1_tex r2_title r2_tex r3_title r3_tex r4_title r4_tex t_title t_tex nh_tex nb1_tex nd1_tex nb2_tex nd2_tex nr1_tex nr2_tex nr3_tex nr4_tex C Z kipin Nmm outer centerline roundc sharpc axestemp subfig sfia
%output from propout and loading
global A xcg zcg Ixx Izz Ixz thetap I11 I22 Cw J outfy_tex unsymm restrained Bas_Adv scale_w Xs Ys w scale_tex_w outPedit outMxxedit outMzzedit outM11edit outM22edit outTedit outBedit outL_Tedit outx_Tedit Pcheck Mxxcheck Mzzcheck M11check M22check Tcheck screen axesprop axesstres scale_tex maxstress_tex minstress_tex
%output from boundary condition (Bound. Cond.)
global ed_m ed_neigs solutiontype togglesignature togglegensolution popup_BC toggleSolution Plengths Pm_all Hlengths Hm_all subfig lengthindex axeslongtshape longitermindex txt_longterm len_cur len_longterm longshape_cur jScrollPane_edm jViewPort_edm jEditbox_edm hjScrollPane_edm
%output from cFSM
global toggleglobal toggledist togglelocal toggleother ed_global ed_dist ed_local ed_other NatBasis ModalBasis toggleCouple popup_load axesoutofplane axesinplane axes3d lengthindex modeindex spaceindex longitermindex b_v_view modename spacename check_3D cutface_edit len_cur mode_cur space_cur longterm_cur modes SurfPos scale twod threed undef scale_tex
%output from compareout
global pathname filename pathnamecell filenamecell propcell nodecell elemcell lengthscell curvecell clascell shapescell springscell constraintscell GBTconcell solutiontypecell BCcell m_allcell filedisplay files fileindex modes modeindex mmodes mmodeindex lengthindex axescurve togglelfvsmode togglelfvslength curveoption ifcheck3d minopt logopt threed undef len_plot lf_plot mode_plot SurfPos cutsurf_tex filename_plot len_cur scale_tex mode_cur mmode_cur file_cur xmin_tex xmax_tex ymin_tex ymax_tex filetoplot_tex screen popup_plot filename_title2 clasopt popup_classify times_classified toggleclassify classification_results plength_cur pfile_cur togglepfiles toggleplength mlengthindex mfileindex axespart_title axes2dshape axes3dshape axesparticipation axescurvemode  modedisplay modestoplot_tex
%
%
%template
subfig=figure;
name=['CUFSM v',version,' -- C and Z Template'];
set(subfig,'Name',name,'NumberTitle','off');
set(subfig,'MenuBar','none');
set(subfig,'position',[50 50 800 500])%
%
%------------------------------------------------------------------------------------
%
%
%
%
%DEFINE THE AXIS THAT WILL BE USED FOR THE TWO PLOTS
axestemp=axes('Units','normalized','Position',[0.42 0.1 0.54 0.8],'visible','off');
%
%
%Set default initial values if first time into template
%default set to 
    h=6;
    b1=2;
    b2=2;
    d1=0.5;
    d2=0.5;
    r1=0.15;
    r2=0.15;
    r3=0.15;
    r4=0.15;
    q1=90;
    q2=90;
    t=0.06;
    C=1;
    Z=0;
    CorZ=1;
    kipin=1;
    Nmm=0;
    centerline=0;
    outer=1;
    nh=4;
    nb1=4;
    nb2=4;
    nd1=4;
    nd2=4;
    nr1=4;
    nr2=4;
    nr3=4;
    nr4=4;
%default plot
[prop,node,elem,halfwavelengths,springs,constraints,geom,cz]=templatecalc(CorZ,h,b1,b2,d1,d2,r1,r2,r3,r4,q1,q2,t,nh,nb1,nb2,nd1,nd2,nr1,nr2,nr3,nr4,kipin,centerline);
%flags:[node# element# mat# stress# stresspic coord constraints springs origin] 1 means show
flags=[0 0 0 0 0 0 0 0 1];
crossect(node,elem,axestemp,springs,constraints,flags);
templatepic(node,elem,axestemp,geom,h,b1,d1,q1,b2,d2,q2,r1,r2,r3,r4,t,cz,centerline);
%
%
%GUI CONTROLS FOLLOW
%-------------------
tog_title=uicontrol(subfig,...
	'Style','text','units','normalized',...
   'Position',[0.02 0.94 0.15 0.04],...
	'FontSize',12,'HorizontalAlignment','Left',...
    'String','Template Options:');
%SFIA sections dropdownbox
sfia_title=uicontrol(subfig,...
	'Style','text','units','normalized',...
   'Position',[0 0.89 0.15 0.04],...
   'HorizontalAlignment','Right',...
    'String','SFIA section:');
[labels,data] = sfiadata();
sfia=uicontrol(subfig,...
	'Style','popupmenu','units','normalized',...
   'Position',[0.16 0.89 0.2 0.04],...
   'HorizontalAlignment','Right',...
    'String',labels,...
   'CallBack',[...
		'template_cb(13);']);
%C/Z toggle
CZ_title=uicontrol(subfig,...
	'Style','text','units','normalized',...
   'Position',[0 0.9-0.05 0.15 0.04],...
   'HorizontalAlignment','Right',...
    'String','Cross-section type:');
C=uicontrol(subfig,...
   'Style','radio','units','normalized',...
   'Position',[0.16 0.9-0.05 0.1 0.04],...
   'String','C',...
   'Value',1,...
   'CallBack',[...
		'template_cb(2);']);
Z=uicontrol(subfig,...
   'Style','radio','units','normalized',...
   'Position',[0.26 0.9-0.05 0.1 0.04],...
   'String','Z',...
   'Value',0,...
   'CallBack',[...
 		'template_cb(3);']);
%dimensions toggle
dim_title=uicontrol(subfig,...
	'Style','text','units','normalized',...
   'Position',[0 0.86-0.05 0.15 0.04],...
   'HorizontalAlignment','Right',...
	'String','Dimensions:');
centerline=uicontrol(subfig,...
   'Style','radio','units','normalized',...
   'Position',[0.16 0.86-0.05 0.1 0.04],...
   'String','centerline',...
   'Value',0,...
   'CallBack',[...
		'template_cb(8);']);
outer=uicontrol(subfig,...
   'Style','radio','units','normalized',...
   'Position',[0.26 0.86-0.05 0.1 0.04],...
   'String','Out-to-out H,B,D and inner radii',...
   'Value',1,...
    'Tooltip','Out-to-out H,B,D and inner radii',...
   'CallBack',[...
		'template_cb(9);']);
%sharp round corner toggler
corner_title=uicontrol(subfig,...
	'Style','text','units','normalized',...
   'Position',[0 0.82-0.05 0.15 0.04],...
   'HorizontalAlignment','Right',...
	'String','Corner modeling:');
sharpc=uicontrol(subfig,...
   'Style','radio','units','normalized',...
   'Position',[0.16 0.82-0.05 0.1 0.04],...
   'String','sharp',...
   'Value',0,...
   'CallBack',[...
		'template_cb(10);']);
roundc=uicontrol(subfig,...
   'Style','radio','units','normalized',...
   'Position',[0.26 0.82-0.05 0.1 0.04],...
   'String','round',...
   'Value',1,...
   'CallBack',[...
		'template_cb(11);']);
%units toggle
units_title=uicontrol(subfig,...
	'Style','text','units','normalized',...
   'Position',[0 0.78-0.05 0.15 0.04],...
   'HorizontalAlignment','Right',...
	'String','material (steel) units:');
kipin=uicontrol(subfig,...
   'Style','radio','units','normalized',...
   'Position',[0.16 0.78-0.05 0.1 0.04],...
   'String','kip&in.',...
   'Value',1,...
   'CallBack',[...
		'template_cb(5);']);
Nmm=uicontrol(subfig,...
   'Style','radio','units','normalized',...
   'Position',[0.26 0.78-0.05 0.1 0.04],...
   'String','N&mm',...
   'Value',0,...
   'CallBack',[...
		'template_cb(6);']);

%
leaveandsubmit=uicontrol(subfig,...
	'Style','push','units','normalized',...
	'Position',[0.02 0.01 0.12 0.06],...
	'String','Submit to Input',...
    'BackgroundColor','g',...
	'Callback',[...
		'template_cb(4);']);
savesection=uicontrol(subfig,...
	'Style','push','units','normalized',...
	'Position',[0.15 0.01 0.12 0.06],...
	'String','Save Section',...
    'BackgroundColor','[1 1 1]',...
	'Callback',[...
		'template_cb(12);']);
closetemplate=uicontrol(subfig,...
	'Style','push','units','normalized',...
	'Position',[0.28 0.01 0.12 0.06],...
	'String','Close (don''t submit)',...
    'BackgroundColor','r',...   
   'Callback',[...
		'template_cb(7);']);
%
%
%
%DIMENSIONS
%------------------------------------------------------------------------
dim2_title=uicontrol(subfig,...
	'Style','text','units','normalized',...
   'Position',[0.02 0.74-0.05 0.4 0.04],...
	'FontSize',12,'HorizontalAlignment','Left',...
    'String','Section Dimensions:');
%L column
h_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0 0.7-0.05 0.075 0.04],...
    'String','h');
b1_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0 0.65-0.05 0.075 0.04],...
    'String','b1');
d1_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0 0.6-0.05 0.075 0.04],...
    'String','d1');
q1_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0 0.55-0.05 0.075 0.04],...
    'String','theta1');
r1_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0 0.5-0.05 0.075 0.04],...
    'String','rcL1');
r2_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0 0.45-0.05 0.075 0.04],...
    'String','rcL2');
%R column
t_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0.2 0.7-0.05 0.075 0.04],...
    'String','t');
b2_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0.2 0.65-0.05 0.075 0.04],...
    'String','b2');
d2_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0.2 0.60-0.05 0.075 0.04],...
    'String','d2');
q2_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0.2 0.55-0.05 0.075 0.04],...
    'String','theta2');
r3_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0.2 0.50-0.05 0.075 0.04],...
    'String','rcL3');
r4_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0.2 0.45-0.05 0.075 0.04],...
    'String','rcL4');
%
%L column
h_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
   'Position',[0.08 0.7-0.05 0.12 0.04],...
	'String',num2str(h),...
   'Callback',[...
		'template_cb(1);']);
b1_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
	'Position',[0.08 0.65-0.05 0.12 0.04],...
	'String',num2str(b1),...%);
    'Callback',[...
		'template_cb(1);']);
d1_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
	'Position',[0.08 0.6-0.05 0.12 0.04],...
	'String',num2str(d1),...%);
    'Callback',[...
		'template_cb(1);']);
q1_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
	'Position',[0.08 0.55-0.05 0.12 0.04],...
	'String',num2str(q1),...%);
    'Callback',[...
		'template_cb(1);']);
r1_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
	'Position',[0.08 0.5-0.05 0.12 0.04],...
	'String',num2str(r1),...%);
    'Callback',[...
		'template_cb(1);']);
r2_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
	'Position',[0.08 0.45-0.05 0.12 0.04],...
	'String',num2str(r2),...%);
    'Callback',[...
		'template_cb(1);']);
%R column    
t_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
   'Position',[0.28 0.7-0.05 0.12 0.04],...
	'String',num2str(t),...%);
    'Callback',[...
		'template_cb(1);']);
b2_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
	'Position',[0.28 0.65-0.05 0.12 0.04],...
	'String',num2str(b2),...%);
    'Callback',[...
		'template_cb(1);']);
d2_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
	'Position',[0.28 0.60-0.05 0.12 0.04],...
	'String',num2str(d2),...%);
    'Callback',[...
		'template_cb(1);']);
q2_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
	'Position',[0.28 0.55-0.05 0.12 0.04],...
	'String',num2str(q2),...%);
    'Callback',[...
		'template_cb(1);']);
r3_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
	'Position',[0.28 0.5-0.05 0.12 0.04],...
	'String',num2str(r3),...%);
    'Callback',[...
		'template_cb(1);']);
r4_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
	'Position',[0.28 0.45-0.05 0.12 0.04],...
	'String',num2str(r4),...%);
    'Callback',[...
		'template_cb(1);']);
%Change the default to outer, so set that here
set(centerline,'Value',0);
set(outer,'Value',1);
set(h_title,'String','H');
set(b1_title,'String','B1');
set(d1_title,'String','D1');
set(q1_title,'String','Theta1');
set(r1_title,'String','ri1');
set(r2_title,'String','ri2');
set(t_title,'String','t');
set(b2_title,'String','B2');
set(d2_title,'String','D2');
set(q2_title,'String','Theta2');
set(r3_title,'String','ri3');
set(r4_title,'String','ri4');    
%------------------------------------------------------------------------
%
%DISCRETIZATION
%------------------------------------------------------------------------
disc_title=uicontrol(subfig,...
	'Style','text','units','normalized',...
   'Position',[0.02 0.39-0.05 0.4 0.04],...
	'FontSize',12,'HorizontalAlignment','Left',...
    'String','Element Discretization:');
%L column
nh_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0 0.35-0.05 0.075 0.04],...
    'String','nh');
nb1_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0 0.30-0.05 0.075 0.04],...
    'String','nb1');
nd1_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0 0.25-0.05 0.075 0.04],...
    'String','nd1');
nr1_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0 0.20-0.05 0.075 0.04],...
    'String','nrcL1');
nr2_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0 0.15-0.05 0.075 0.04],...
    'String','nrcL2');
%R column
% nt_title=uicontrol(subfig,...
%     'Style','text','units','normalized',...
%    'Position',[0.2 0.35 0.075 0.04],...
%     'String','t');
nb2_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0.2 0.30-0.05 0.075 0.04],...
    'String','nb2');
nd2_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0.2 0.25-0.05 0.075 0.04],...
    'String','nd2');
nr3_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0.2 0.20-0.05 0.075 0.04],...
    'String','nrcL3');
nr4_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
   'Position',[0.2 0.15-0.05 0.075 0.04],...
    'String','nrcL4');
%
%L column
nh_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
   'Position',[0.08 0.35-0.05 0.12 0.04],...
	'String','4',...
   'Callback',[...
		'template_cb(1);']);
nb1_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
	'Position',[0.08 0.30-0.05 0.12 0.04],...
	'String','4',...%);
    'Callback',[...
		'template_cb(1);']);
nd1_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
	'Position',[0.08 0.25-0.05 0.12 0.04],...
	'String','4',...%);
    'Callback',[...
		'template_cb(1);']);
nr1_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
	'Position',[0.08 0.20-0.05 0.12 0.04],...
	'String','4',...%);
    'Callback',[...
		'template_cb(1);']);
nr2_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
	'Position',[0.08 0.15-0.05 0.12 0.04],...
	'String','4',...%);
    'Callback',[...
		'template_cb(1);']);
%R column    
% nt_tex=uicontrol(subfig,...
% 	'Style','edit','units','normalized',...
%    'Position',[0.28 0.35 0.12 0.04],...
% 	'String',num2str(t),...%);
%     'Callback',[...
% 		'template_cb(1);']);
nb2_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
	'Position',[0.28 0.30-0.05 0.12 0.04],...
	'String','4',...%);
    'Callback',[...
		'template_cb(1);']);
nd2_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
	'Position',[0.28 0.25-0.05 0.12 0.04],...
	'String','4',...%);
    'Callback',[...
		'template_cb(1);']);
nr3_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
	'Position',[0.28 0.20-0.05 0.12 0.04],...
	'String','4',...%);
    'Callback',[...
		'template_cb(1);']);
nr4_tex=uicontrol(subfig,...
	'Style','edit','units','normalized',...
	'Position',[0.28 0.15-0.05 0.12 0.04],...
	'String','4',...%);
    'Callback',[...
		'template_cb(1);']);
%
% updateplot=uicontrol(subfig,...
% 	'Style','push','units','normalized',...
% 	'Position',[0.75 0.95 0.15 0.05],...
% 	'String','Update Plot',...
% 	'Callback',[...
% 		'template_cb(1);']);
% exittemplate=uicontrol(subfig,...
% 	'Style','push','units','normalized',...
% 	'Position',[0.9 0.95 0.1 0.05],...
% 	'String','EXIT',...
%    'Callback',[...
% 		'template_cb(7);']);
%
note_title=uicontrol(subfig,...
	'Style','text','units','normalized',...
   'Position',[0.4 0.0 0.6 0.05],...
	'String','Note, template is one-way, i.e. for model creation only (centerline dimensons indicated on plot)');
%
%
%%
